
import { Therapist } from './types';

export const SPECIALTIES = [
    "Sports Injury",
    "Post-Op Recovery",
    "Neurological Rehab",
    "Pediatric",
    "Geriatric",
    "Orthopedic",
    "Cardiopulmonary"
];

export const MOCK_THERAPISTS: Therapist[] = [
  {
    id: 1,
    name: 'Dr. Ankita Mishra',
    email: 'ankita.mishra.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 5.0,
    reviewCount: 51,
    specialties: ['Physiotherapist', 'Neuro Physiotherapist', 'Orthopedic Physiotherapist'],
    description: 'Dr. Ankita Mishra is a Physiotherapist, Neuro Physiotherapist and Orthopedic Physiotherapist in Kharghar, Navi Mumbai and has an experience of 6 years in these fields. Dr. Ankita Mishra practices at Advanced Key Physiotherapy in Kharghar, Navi Mumbai. She completed MPT - Orthopedic Physiotherapy from Mahatma Gandhi Medical College & Hospital, Jaipur in 2016 and BPTh/BPT from Mahatma Gandhi Medical College & Hospital, Jaipur in 2012.',
    qualifications: ['MPTh/MPT - Orthopedic Physiotherapy', 'BPTh/BPT'],
    clinicPhotos: [],
    reviews: [],
    fee: 500,
    isProfileClaimed: true,
    experience: 13,
    specialistExperience: 6,
    patientSatisfaction: 100,
    clinic: {
        name: 'Advanced Key Physiotherapy',
        address: 'Kharghar, Navi Mumbai',
        rating: 5,
        timings: {
            days: 'Mon - Sat',
            hours: ['10:00 AM - 08:00 PM']
        },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true,
        phone: '074988 52881'
    }
  },
  {
    id: 2,
    name: 'Dr. Shilpa Rangari',
    email: 'shilpa.rangari.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 5.0,
    reviewCount: 137,
    specialties: ['Physiotherapist', 'Cardiovascular & Pulmonary Physiotherapist', 'Geriatric Physiotherapist'],
    description: 'I am practicing from last twenty years. I have treated maximum types of physiotherapy requiring patients.',
    qualifications: ['BPTh/BPT', 'MPTh/MPT - Cardiovascular & Pulmonary Physiotherapist'],
    clinicPhotos: ['https://picsum.photos/id/10/800/600', 'https://picsum.photos/id/20/800/600', 'https://picsum.photos/id/30/800/600', 'https://picsum.photos/id/40/800/600', 'https://picsum.photos/id/50/800/600'],
    fee: 500,
    isProfileClaimed: true,
    experience: 25,
    specialistExperience: 20,
    patientSatisfaction: 97,
    clinic: {
        name: 'Mattrix Advanced Physiotherapy Clinic and Pain Clinic Center',
        address: 'Balaji Swaroop, Shop Number 1, Plot Number 32, Sector 19, Landmark: Opposite Namra Heights and Brijesh Tutorials, Navi Mumbai',
        rating: 5.0,
        timings: {
            days: 'Mon - Sat',
            hours: ['09:30 AM - 01:00 PM', '05:00 PM - 08:00 PM']
        },
        isOnlinePaymentAvailable: true,
        isPrime: true,
        maxWaitTime: 15,
        isVerified: true,
        phone: '093232 16714'
    },
    reviews: [
      { id: 1, patientName: 'John D.', rating: 5, comment: 'Shilpa was fantastic! My shoulder feels better than ever.', date: '2023-10-15' },
      { id: 2, patientName: 'Sarah K.', rating: 5, comment: 'Very knowledgeable and professional. Highly recommend.', date: '2023-09-22' },
    ],
  },
  {
    id: 3,
    name: 'Dr. Aditi Potkar',
    email: 'aditi.potkar.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 5.0,
    reviewCount: 19,
    specialties: ['Therapist', 'Physiotherapist'],
    description: 'Dr. Aditi Potkar (PT) is a physiotherapist and a keen advocate of a healthy lifestyle. She believes that accurate, relevant and timely intervention helps restore a patient to normalcy. For this reason, she has always stressed on dedicated care for all her patients. Physiotherapy, as you all must be aware, is a dynamic profession which uses a range of treatment techniques to restore movement and function within the body. She has close to 19 years\' experience in home care therapy. She is a member of The Indian Association of Physiotherapists and also registered with the Maharashtra State OT-PT Council.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: [],
    fee: 500,
    isProfileClaimed: true,
    experience: 21,
    specialistExperience: 19,
    patientSatisfaction: 100,
    clinic: {
        name: 'Wellness Helpers',
        address: 'Kharghar',
        rating: 5,
        timings: {
            days: 'Mon - Sat',
            hours: ['10:00 AM - 07:00 PM']
        },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 0,
        isVerified: true
    },
    reviews: []
  },
  
  {
    id: 4,
    name: 'Dr. Mithila Patil',
    email: 'mithila.patil.physio@example.com',
    title: 'Paediatric Physiotherapist',
    location: 'Kamothe, Navi Mumbai',
    rating: 4.8,
    reviewCount: 18,
    specialties: ['Pediatric Physiotherapy', 'NDT', 'ANC & PNC Physiotherapy'],
    description: 'Dr. Mithila Patil is expert in Pediatric Physiotherapy, she has attended various workshops on NDT & SI. Also she has attended workshops of ANC & PNC.',
    qualifications: ['MPTh/MPT - Paediatric Physiotherapy'],
    clinicPhotos: ['https://picsum.photos/id/11/800/600', 'https://picsum.photos/id/12/800/600'],
    reviews: [],
    fee: 400,
    isProfileClaimed: false,
    experience: 11,
    specialistExperience: 5,
    patientSatisfaction: 94,
    clinic: {
        name: 'Healing Hands Physiotherapy Clinic',
        address: 'Shop Number 14, Plot Number 57/58, Bhoomi Ratna Apartment, Sector 18, Landmark: Near Hari Krishna Furniture Mall, Bank Of Baroda., Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Mon - Sat', hours: ['10:00 AM - 01:00 PM', '04:00 PM - 08:30 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 5,
    name: 'Dr. Richa Nikam',
    email: 'richa.nikam.physio@example.com',
    title: 'Geriatric Physiotherapist',
    location: 'Kamothe, Navi Mumbai',
    rating: 5.0,
    reviewCount: 39,
    specialties: ['Geriatric Physiotherapist', 'Orthopedic'],
    description: 'Dr. Richa Nikam is a Physiotherapist and Geriatric Physiotherapist in Kamothe, Navi Mumbai and has an experience of 15 years in these fields.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/21/800/600'],
    reviews: [],
    fee: 1500,
    isProfileClaimed: true,
    experience: 15,
    specialistExperience: 15,
    patientSatisfaction: 100,
    clinic: {
        name: 'Dr. Richa Nikam Physiotherapy Clinic',
        address: 'Shop Number 7, Samarpan Homeopathy clinic, Pratik Gardens, Sector 34., Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Mon - Sat', hours: ['09:00 AM - 11:00 AM', '02:00 PM - 06:00 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: true,
        maxWaitTime: 10,
        isVerified: true
    }
  },
  {
    id: 6,
    name: 'Dr. Ruchi Shukla',
    email: 'ruchi.shukla.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kamothe, Navi Mumbai',
    rating: 3.5,
    reviewCount: 4,
    specialties: ['Interferential Therapy', 'Sports Fracture Rehabilitation', 'Gait Training'],
    description: 'Dr. Ruchi Shukla has 14 years of experience and practices at Global Health Care Orthopedics & Gynecology Hospital. Services include Interferential Therapy, Electrical Stimulation, and Sports Fracture Rehabilitation.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/31/800/600', 'https://picsum.photos/id/32/800/600', 'https://picsum.photos/id/33/800/600'],
    reviews: [],
    fee: 300,
    isProfileClaimed: false,
    experience: 14,
    specialistExperience: 14,
    patientSatisfaction: 88,
    clinic: {
        name: 'Global Health Care Orthopedics & Gynecology Hospital',
        address: 'Shop 6,7,8, Chaturth CHS, Plot 33, Sector -12, Landmark: Near Mansarowar Station Road., Navi Mumbai',
        rating: 3.5,
        timings: { days: 'Mon - Sun', hours: ['ON - CALL'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 30,
        isVerified: true
    }
  },
  {
    id: 7,
    name: 'Dr. Swapnil Sargar',
    email: 'swapnil.sargar.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kamothe, Navi Mumbai',
    rating: 4.5,
    reviewCount: 5,
    specialties: ['Ortho', 'Neuro rehabilitation', 'Cupping', 'Dry Needling'],
    description: 'Dr Swapnil Sargar completed his Bachelor\'s degree from prestigious Seth GSMC and KEMH, Mumbai. He runs the biggest physiotherapy setup in Panvel & Navi Mumbai region, specializing in Ortho and Neuro rehabilitation.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/41/800/600', 'https://picsum.photos/id/42/800/600', 'https://picsum.photos/id/43/800/600'],
    reviews: [],
    fee: 350,
    isProfileClaimed: true,
    experience: 8,
    specialistExperience: 5,
    patientSatisfaction: 96,
    clinic: {
        name: 'New Life Physiotherapy And Rehabilitation Center',
        address: 'Plot Number 12, Alankapuri CHS, F-104, Sector 10, Landmark: Beside Union Bank Of India, Navi Mumbai',
        rating: 4.5,
        timings: { days: 'Mon - Sat', hours: ['10:30 AM - 02:00 PM', '05:00 PM - 09:00 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: false,
        maxWaitTime: 20,
        isVerified: true
    }
  },
  {
    id: 8,
    name: 'Dr. Sujitkumar Patil',
    email: 'sujitkumar.patil.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kamothe, Navi Mumbai',
    rating: 4.6,
    reviewCount: 1,
    specialties: ['Sports Injury Rehabilitation', 'Tape Stripping', 'Sports Physiotherapy'],
    description: 'Dr. Sujitkumar Patil has 17 years of experience. He completed BPTh/BPT from Maharashtra University of Health Sciences, Nashik in 2008.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: [],
    reviews: [],
    fee: 100,
    isProfileClaimed: true,
    experience: 17,
    specialistExperience: 17,
    patientSatisfaction: 92,
    clinic: {
        name: 'Purna Physiotherapy Clinic',
        address: 'Shop No. 1 & 2, Slot No. 87, Awas Building, Sector 19, Ahandeshwar Station Road, Landmark: Near Milk and Sweets Shop, Navi Mumbai',
        rating: 4.6,
        timings: { days: 'Mon - Sat', hours: ['09:00 AM - 02:00 PM', '05:00 PM - 10:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 25,
        isVerified: true
    }
  },
  {
    id: 9,
    name: 'Dr. Dharmendra Patel',
    email: 'dharmendra.patel.physio@example.com',
    title: 'Physiotherapist',
    location: 'Panvel, Navi Mumbai',
    rating: 4.7,
    reviewCount: 12,
    specialties: ['Cupping Therapy', 'Physiotherapy Rehab', 'Dry Needling'],
    description: 'Dr. Dharmendra Patel has 9 years of experience. He completed BPTh/BPT from Sumandeep Vidyapith University, Vadodara in 2016.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/51/800/600'],
    reviews: [],
    fee: 300,
    isProfileClaimed: true,
    experience: 9,
    specialistExperience: 9,
    patientSatisfaction: 95,
    clinic: {
        name: 'Healthy Spine Physiotherapy Clinic',
        address: 'Shop Number- 34, Ground Floor, Sky Avenue, Sector 34, Panvel., Navi Mumbai',
        rating: 4.7,
        timings: { days: 'Mon - Sat', hours: ['09:30 AM - 01:00 PM', '04:30 PM - 08:30 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 10,
    name: 'Dr. Rutuja Kamble',
    email: 'rutuja.kamble.physio@example.com',
    title: 'Cardiovascular & Pulmonary Physiotherapist',
    location: 'Kamothe, Navi Mumbai',
    rating: 4.9,
    reviewCount: 1,
    specialties: ['Cardiovascular Physiotherapy', 'Pulmonary Physiotherapy'],
    description: 'Dr. Rutuja Kamble has 5 years of experience. She completed MPTh/MPT from Maharashtra University of Health Sciences, Nashik in 2020.',
    qualifications: ['MPTh/MPT - Cardiovascular & Pulmonary Physiotherapy'],
    clinicPhotos: [],
    reviews: [],
    fee: 500,
    isProfileClaimed: true,
    experience: 5,
    specialistExperience: 5,
    patientSatisfaction: 98,
    clinic: {
        name: 'PhysioK',
        address: 'Shop 15, Shubhsharnam Complex, Plot 21. Landmark: Beside Dr Kshirsagar Clinic, Navi Mumbai',
        rating: 4.9,
        timings: { days: 'Mon - Sat', hours: ['06:00 PM - 10:00 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: true,
        maxWaitTime: 10,
        isVerified: true
    }
  },
  {
    id: 11,
    name: 'Dr. Neelam Patel',
    email: 'neelam.patel.physio@example.com',
    title: 'Sports and Musculoskeletal Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 4.8,
    reviewCount: 47,
    specialties: ['Sports Physiotherapy', 'Manual Therapy', 'Mulligan\'s Technique', 'Dry Needling'],
    description: 'Dr. Neelam Patel is an expert in assessing sports specific athletes\' physical abilities and has hands-on experience in planning and implementing sports physiotherapy programs. She has a vast experience in treating masters, national and international marathoners, badminton, hockey athletes.',
    qualifications: ['MPTh/MPT - Sports Physiotherapy'],
    clinicPhotos: [],
    reviews: [],
    fee: 2500,
    isProfileClaimed: true,
    experience: 11,
    specialistExperience: 11,
    patientSatisfaction: 96,
    clinic: {
        name: 'Athena Sport Physiotherapy Centre',
        address: 'Om Apartment, 1st Floor, B Wing, Flat Number 102, Sector 20, Panvel., Landmark: next to park view or phoenix hospital, opposite dyna mart',
        rating: 4.8,
        timings: { days: 'Sun', hours: ['10:00 AM - 08:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 20,
        isVerified: true
    }
  },
  {
    id: 13,
    name: 'Dr. Suman Gupta',
    email: 'suman.gupta.physio@example.com',
    title: 'Orthopedic Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 5.0,
    reviewCount: 384,
    specialties: ['Orthopedic Physiotherapist', 'Clinical Physiotherapist', 'Sports and Musculoskeletal Physiotherapist'],
    description: 'Dr. Suman Gupta (PT) is an Orthopedic Physiotherapist, Clinical Physiotherapist and Physiotherapist in Kharghar, Navi Mumbai and has an experience of 5 years in these fields. She completed BPTh/BPT from Dr. DY Patil Medical College & Hospital in 2012.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: [],
    reviews: [],
    fee: 700,
    isProfileClaimed: true,
    experience: 13,
    specialistExperience: 5,
    patientSatisfaction: 95,
    clinic: {
        name: 'Prohealth Bone and Joint Specialty Clinic',
        address: 'Shop Number 1, Shree Balaji Krupa, Plot Number 19A, Sector 20, Landmark: Beside Bank Of Baroda., Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Mon - Sat', hours: ['11:00 AM - 02:00 PM', '05:00 PM - 09:00 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: true,
        maxWaitTime: 10,
        isVerified: true
    }
  },
  {
    id: 14,
    name: 'Dr. Krutika Gauhar',
    email: 'krutika.gauhar.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 4.0,
    reviewCount: 12,
    specialties: ['Orthopedic', 'Post-Op Recovery'],
    description: 'Dr. Krutika Gauhar is a Physiotherapist in Kharghar, Navi Mumbai and has an experience of 10 years in this field. Dr. Krutika Gauhar practices at Motherhood Hospital in Kharghar, Navi Mumbai. She completed BPTh/BPT from MGM School Of Physiotherapy in 2015.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/61/800/600', 'https://picsum.photos/id/62/800/600', 'https://picsum.photos/id/63/800/600'],
    reviews: [],
    fee: 600,
    isProfileClaimed: false,
    experience: 10,
    specialistExperience: 10,
    patientSatisfaction: 90,
    clinic: {
        name: 'Motherhood Hospital',
        address: 'Sector 7 Kharghar, Landmark: Opposite Shah Kingdom, Navi Mumbai',
        rating: 4.0,
        timings: { days: 'Mon - Sun', hours: ['ON - CALL'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 25,
        isVerified: true
    }
  },
  {
    id: 15,
    name: 'Dr. Poonam Dabas',
    email: 'poonam.dabas.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 4.0,
    reviewCount: 9,
    specialties: ['General Physiotherapy', 'Rehabilitation'],
    description: 'Dr. Poonam Dabas is a Physiotherapist in Kharghar, Navi Mumbai and has an experience of 13 years in this field.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/71/800/600', 'https://picsum.photos/id/72/800/600', 'https://picsum.photos/id/73/800/600', 'https://picsum.photos/id/74/800/600'],
    reviews: [],
    fee: 250,
    isProfileClaimed: true,
    experience: 13,
    specialistExperience: 13,
    patientSatisfaction: 91,
    clinic: {
        name: 'Om Navjeevan Hospital',
        address: '2, Sector 21, Tata Hospital Road, Landmark: Near to Iskon Temple, Navi Mumbai',
        rating: 4.0,
        timings: { days: 'Mon - Sat', hours: ['12:00 PM - 02:00 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: false,
        maxWaitTime: 20,
        isVerified: true
    }
  },
  {
    id: 16,
    name: 'Dr. Sushmita Suraj',
    email: 'sushmita.suraj.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 4.0,
    reviewCount: 5,
    specialties: ['Personalised Treatment Plans', 'Individualised Assessment', 'Sports Injury Rehabilitation'],
    description: 'Dr. Sushmita Suraj is a Physiotherapist in Kharghar, Navi Mumbai and has an experience of 13 years in this field. Dr. Sushmita Suraj practices at Om Navjeevan Hospital in Kharghar, Navi Mumbai. She completed BPTh/BPT from Terna Physiotherapy College in 2011.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/81/800/600', 'https://picsum.photos/id/82/800/600', 'https://picsum.photos/id/83/800/600'],
    reviews: [],
    fee: 250,
    isProfileClaimed: true,
    experience: 13,
    specialistExperience: 13,
    patientSatisfaction: 89,
    clinic: {
        name: 'Om Navjeevan Hospital',
        address: '2, Sector 21, Tata Hospital Road, Landmark: Near to Iskon Temple, Navi Mumbai',
        rating: 4.0,
        timings: { days: 'Mon - Sun', hours: ['ON - CALL'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 20,
        isVerified: true
    }
  },
  {
    id: 17,
    name: 'Dr. Pavitra Iyer',
    email: 'pavitra.iyer.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 5.0,
    reviewCount: 10,
    specialties: ['Manual Therapy', 'Dry Needling'],
    description: 'Dr Pavitra Iyer is a Physiotherapist with 5 years of work experience. Her passion for manual therapy lead to her selection as a senior physiotherapist in Capri Spine chain of clinics, a Delhi based physiotherapy franchise in Koregaon Park, Pune. She is a certified manual therapist (COMT,CMTP) Delhi, and a certified Dry needling practitioner (DNP - Dry Needling Association of India), bangalore.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: [],
    reviews: [],
    fee: 600,
    isProfileClaimed: true,
    experience: 9,
    specialistExperience: 5,
    patientSatisfaction: 99,
    clinic: {
        name: 'Impact Diagnostic',
        address: 'Kamal Kunj, F-45/32-&.33, Shivaji Chowk, Block F, Sector 12, Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Sat', hours: ['09:00 AM - 06:00 PM', '06:30 PM - 09:30 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 18,
    name: 'Dr. Sohini Singh',
    email: 'sohini.singh.physio@example.com',
    title: 'Orthopedic & Sports Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 5.0,
    reviewCount: 23,
    specialties: ['Orthopedic Physiotherapist', 'Geriatric Physiotherapist', 'Sports and Musculoskeletal Physiotherapist'],
    description: 'Working as lactation consultant in Navi mumbai.',
    qualifications: ['BPTh/BPT', 'MPTh/MPT - Musculoskeletal Disorders and Sports Physiotherapy'],
    clinicPhotos: [],
    reviews: [],
    fee: 500,
    isProfileClaimed: true,
    experience: 20,
    specialistExperience: 19,
    patientSatisfaction: 100,
    clinic: {
        name: 'Physiotherapy Facility Clinic',
        address: 'Sector -6, Landmark: Near Kalkhondrahalli Bus Stop, Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Mon - Sat', hours: ['10:00 AM - 01:00 PM', '05:00 PM - 08:30 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: true,
        maxWaitTime: 10,
        isVerified: true
    }
  },
  {
    id: 19,
    name: 'Dr. Sucheta Nagare -Mungate',
    email: 'sucheta.nagare.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 4.7,
    reviewCount: 7,
    specialties: ['Musculoskeletal Disorders', 'Neuromuscular Disorders', 'Home Sessions'],
    description: 'Dr. Sucheta Nagare is a Physiotherapist practicing since 2013, experienced to give treatment to patients having Musculoskeletal and Neuromuscular disorders in IPD and OPD form. Also, giving Home sessions.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/91/800/600', 'https://picsum.photos/id/92/800/600'],
    reviews: [],
    fee: 400,
    isProfileClaimed: true,
    experience: 12,
    specialistExperience: 12,
    patientSatisfaction: 96,
    clinic: {
        name: 'Heal Station',
        address: 'Shankeshwar Heights, Shop No. 8, Plot 6, Sector 11, Ryan International School Road, Landmark: Kidzee, Navi Mumbai',
        rating: 4.7,
        timings: { days: 'Mon - Sun', hours: ['10:30 AM - 12:30 PM', '02:30 PM - 07:30 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 20,
        isVerified: true
    }
  },
  {
    id: 20,
    name: 'Dr. Ruchita Parikh',
    email: 'ruchita.parikh.physio@example.com',
    title: 'Physiotherapist',
    location: 'Kharghar, Navi Mumbai',
    rating: 4.9,
    reviewCount: 1,
    specialties: ['Therapist', 'Sports and Musculoskeletal Physiotherapist'],
    description: 'Dr. Ruchita Parikh is a dedicated physiotherapist with 11 years of experience, specializing in musculoskeletal sciences. She is committed to providing excellent care to her patients.',
    qualifications: ['MPTh/MPT - Musculoskeletal Sciences'],
    clinicPhotos: [],
    reviews: [],
    fee: 1000,
    isProfileClaimed: true,
    experience: 11,
    specialistExperience: 11,
    patientSatisfaction: 98,
    clinic: {
        name: 'Physio Matters',
        address: 'Kharghar, Navi Mumbai',
        rating: 4.9,
        timings: {
            days: 'Mon - Fri',
            hours: ['11:00 AM - 02:45 PM', '03:30 PM - 06:30 PM']
        },
        isOnlinePaymentAvailable: true,
        isPrime: true,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 21,
    name: 'Dr. Manasi Patil',
    email: 'manasi.patil.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 5.0,
    reviewCount: 13,
    specialties: ['Physiotherapist', 'Geriatric Physiotherapist'],
    description: 'Dr Manasi Joshi is a practising physiotherapist with experience both in India and the US. She has worked in a variety of multidisciplinary settings.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/101/800/600', 'https://picsum.photos/id/102/800/600'],
    reviews: [],
    fee: 500,
    isProfileClaimed: true,
    experience: 23,
    specialistExperience: 20,
    patientSatisfaction: 98,
    clinic: {
        name: 'Physiotherapy Clinic',
        address: 'Bunglow number 10, plot 56,57, Pleasant view Chs, Sector 14, Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Mon - Sat', hours: ['10:00 AM - 08:00 PM'] },
        isOnlinePaymentAvailable: true,
        isPrime: true,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 22,
    name: 'Dr. Tejal Ghadge',
    email: 'tejal.ghadge.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.9,
    reviewCount: 0,
    specialties: ['Physiotherapist', 'NDT Certified pediatric Physiotherapist'],
    description: 'NDT Certified pediatric Physiotherapist with 11 years of experience.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/111/800/600', 'https://picsum.photos/id/112/800/600', 'https://picsum.photos/id/113/800/600'],
    reviews: [],
    fee: 1000,
    isProfileClaimed: true,
    experience: 11,
    specialistExperience: 11,
    patientSatisfaction: 97,
    clinic: {
        name: 'Sneh Rehabilitation Education and Research centre',
        address: 'A-1, Raja Shantanu, Plot Number 29, Sector-16, Navi Mumbai',
        rating: 4.9,
        timings: { days: 'Mon - Sat', hours: ['09:00 AM - 05:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 23,
    name: 'Dr. Jayamala Ghagare',
    email: 'jayamala.ghagare.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 5.0,
    reviewCount: 2,
    specialties: ['Women Health Physiotherapist', 'Weight Management', 'Clinical Physiotherapist', 'Cupping Therapist', 'Neuro Rehabilitation'],
    description: 'Dr. Jayamala Ghagare is a Physiotherapist in Vashi, Navi Mumbai and has an experience of 18 years in this field. She completed BPTh/BPT from Dr DY Patil University, Navi Mumbai in 2007.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/121/800/600', 'https://picsum.photos/id/122/800/600', 'https://picsum.photos/id/123/800/600'],
    reviews: [],
    fee: 600,
    isProfileClaimed: true,
    experience: 18,
    specialistExperience: 18,
    patientSatisfaction: 100,
    clinic: {
        name: 'Vinamra Swaraj Hospital',
        address: 'Plot Number - 108, 108 A & 109, Sector -11, Landmark: Opposite Shiv Sena Shakha, Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Mon - Sat', hours: ['11:00 AM - 01:00 PM', '08:00 PM - 09:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 24,
    name: 'Dr. Aditi Prabhukeluskar',
    email: 'aditi.prabhu.physio@example.com',
    title: 'Sports and Musculoskeletal Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.8,
    reviewCount: 0,
    specialties: ['Sports Physiotherapist', 'Musculoskeletal Physiotherapist'],
    description: 'Qualified Sports Physiotherapist with extensive experience in managing orthopedic and sports condition. Have worked closely with ultraendurance cyclists for over 2 years.',
    qualifications: ['BPTh/BPT', 'MPT/MPTh - Sports Medicine'],
    clinicPhotos: ['https://picsum.photos/id/131/800/600', 'https://picsum.photos/id/132/800/600', 'https://picsum.photos/id/133/800/600'],
    reviews: [],
    fee: 650,
    isProfileClaimed: true,
    experience: 7,
    specialistExperience: 3,
    patientSatisfaction: 95,
    clinic: {
        name: 'Trisamya centre for Photomedicine',
        address: '1801, Fairmount, above zudio, Plot No. 4, Sector 17, Off, Palm Beach Rd (service road), Sanpada, Navi Mumbai, Maharashtra 400705, Landmark: wellness Health clinic, Navi Mumbai',
        rating: 4.8,
        timings: { days: 'Mon - Sun', hours: ['09:00 AM - 10:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 25,
    name: 'Dr. Priyanka Pinto',
    email: 'priyanka.pinto.physio@example.com',
    title: 'Sports and Musculoskeletal Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.7,
    reviewCount: 0,
    specialties: ['Sports Taping', 'Geriatric Physiotherapist', 'Physiotherapy Rehab', 'Dry Needling'],
    description: 'Dr. Priyanka Pinto is a Sports and Musculoskeletal Physiotherapist in Vashi, Navi Mumbai and has an experience of 7 years in this field. She completed MPTh/MPT - Musculoskeletal Physiotherapy from NMIMS in 2018.',
    qualifications: ['MPTh/MPT - Musculoskeletal Physiotherapy'],
    clinicPhotos: ['https://picsum.photos/id/141/800/600', 'https://picsum.photos/id/142/800/600', 'https://picsum.photos/id/143/800/600'],
    reviews: [],
    fee: 1500,
    isProfileClaimed: false,
    experience: 7,
    specialistExperience: 2,
    patientSatisfaction: 94,
    clinic: {
        name: 'Replay Physiotherapy',
        address: '1310, Satra Plaza, Palm Beach Road, Vashi Navi Mumbai, Landmark: Sector 14, Navi Mumbai',
        rating: 4.7,
        timings: { days: 'Mon - Sat', hours: ['12:00 PM - 08:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 26,
    name: 'Dr. Sneha More',
    email: 'sneha.more.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.8,
    reviewCount: 6,
    specialties: ['Ortho and sports rehabilitation', "Women's health", 'Pediatric rehabilitation', 'Certified orthopedic manual therapist'],
    description: "Dr. Sneha More-Vaidya currently working as a consultant physiotherapist rehabilitation expert in ortho and sports rehabilitation, women's health and pediatric rehabilitation.",
    qualifications: ['BPTh/BPT'],
    clinicPhotos: [],
    reviews: [],
    fee: 500,
    isProfileClaimed: true,
    experience: 9,
    specialistExperience: 8,
    patientSatisfaction: 96,
    clinic: {
        name: 'Snehal rehabilitation clinic',
        address: 'Room Number 45, SS-1, 203, A/2, Sector-2, Landmark: Near to Ganesh Mandir and Opposite to Bank of Maharashtra, Navi Mumbai',
        rating: 4.8,
        timings: { days: 'Mon - Sun', hours: ['ON - CALL'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 0,
        isVerified: true
    }
  },
  {
    id: 27,
    name: 'Dr. Priyanka Borale',
    email: 'priyanka.borale.physio@example.com',
    title: 'Neuro Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.7,
    reviewCount: 0,
    specialties: ['Orthopedic Physiotherapy', 'Neuro Physiotherapy', 'Individual Physiotherapy'],
    description: 'Dr. Priyanka Borale is a Physiotherapist and Neuro Physiotherapist in Vashi, Navi Mumbai and has an experience of 11 years in these fields.',
    qualifications: ['BPTh/BPT', 'MPTh/MPT - Neurological Physiotherapy'],
    clinicPhotos: ['https://picsum.photos/id/151/800/600', 'https://picsum.photos/id/152/800/600', 'https://picsum.photos/id/153/800/600'],
    reviews: [],
    fee: 1000,
    isProfileClaimed: false,
    experience: 11,
    specialistExperience: 4,
    patientSatisfaction: 95,
    clinic: {
        name: 'Sneh Rehabilitation Education and Research centre',
        address: 'A-1, Raja Shantanu, Plot Number 29, Sector-16, Navi Mumbai',
        rating: 4.7,
        timings: { days: 'Mon - Sun', hours: ['ON - CALL'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 0,
        isVerified: true
    }
  },
  {
    id: 28,
    name: 'Dr. Kirti Shinde',
    email: 'kirti.shinde.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.6,
    reviewCount: 0,
    specialties: ['Manual Therapy'],
    description: 'Dr. Kirti Shinde is a Physiotherapist in Vashi, Navi Mumbai and has an experience of 9 years in this field. She completed BPTh/BPT from DY Patil University in 2016.',
    qualifications: ['BPTh/BPT', 'Certificate of Manual Therapy-COMT'],
    clinicPhotos: ['https://picsum.photos/id/161/800/600', 'https://picsum.photos/id/162/800/600', 'https://picsum.photos/id/163/800/600'],
    reviews: [],
    fee: 1000,
    isProfileClaimed: false,
    experience: 9,
    specialistExperience: 9,
    patientSatisfaction: 93,
    clinic: {
        name: 'Sneh Rehabilitation Education and Research centre',
        address: 'A-1, Raja Shantanu, Plot Number 29, Sector-16, Navi Mumbai',
        rating: 4.6,
        timings: { days: 'Mon - Sat', hours: ['02:00 PM - 07:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 29,
    name: 'Dr. Dalia David Jerrin',
    email: 'dalia.david.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.8,
    reviewCount: 0,
    specialties: ['General Physiotherapy'],
    description: 'Dr. Dalia David Jerrin is a Physiotherapist in Vashi, Navi Mumbai and has an experience of 8 years in this field.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/171/800/600'],
    reviews: [],
    fee: 400,
    isProfileClaimed: true,
    experience: 8,
    specialistExperience: 8,
    patientSatisfaction: 96,
    clinic: {
        name: "Dr Dalia's D-Physio Clinic",
        address: 'A101, Om Rachna Chs, Sector 17, Landmark: Near Dominos, Navi Mumbai',
        rating: 4.8,
        timings: { days: 'Mon - Sun', hours: ['07:00 AM - 01:00 PM', '01:30 PM - 09:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 30,
    name: 'Dr. Deanne Misquita',
    email: 'deanne.misquita.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 5.0,
    reviewCount: 0,
    specialties: ['Child Birth Educator', 'Lactation Consultant'],
    description: 'Dr. Deanne Misquita, Child Birth Educator & Lactation Consultant in Cloudnine hospitals.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/181/800/600', 'https://picsum.photos/id/182/800/600', 'https://picsum.photos/id/183/800/600'],
    reviews: [],
    fee: 1000,
    isProfileClaimed: false,
    experience: 11,
    specialistExperience: 11,
    patientSatisfaction: 100,
    clinic: {
        name: 'Cloudnine Hospital',
        address: 'Plot No. 17, Palm Beach Galleria, Vashi, Landmark: Near Satra Plaza, Navi Mumbai',
        rating: 5.0,
        timings: { days: 'Mon - Sat', hours: ['10:00 AM - 02:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 31,
    name: 'Dr. Pooja Rajsekar',
    email: 'pooja.rajsekar.physio@example.com',
    title: 'Physiotherapist',
    location: 'Vashi, Navi Mumbai',
    rating: 4.7,
    reviewCount: 0,
    specialties: ['General Physiotherapy'],
    description: 'Dr. Pooja Rajsekar is a Physiotherapist in Vashi, Navi Mumbai and has an experience of 7 years in this field.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: ['https://picsum.photos/id/191/800/600', 'https://picsum.photos/id/192/800/600', 'https://picsum.photos/id/193/800/600'],
    reviews: [],
    fee: 800,
    isProfileClaimed: false,
    experience: 7,
    specialistExperience: 7,
    patientSatisfaction: 94,
    clinic: {
        name: 'Nightingales Home Health Services',
        address: 'BSEL-Tech Park, 504 - B wing, 5th Floor, Sector - 30 A, Landmark: Opposite Vashi Railway Station, Navi Mumbai',
        rating: 4.7,
        timings: { days: 'Mon - Sun', hours: ['08:00 AM - 07:00 PM'] },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true
    }
  },
  {
    id: 32,
    name: 'Dr. Priyanka Mishra',
    email: 'priyanka.mishra.physio@example.com',
    title: 'Physiotherapist',
    location: 'Belapur, Navi Mumbai',
    rating: 5.0,
    reviewCount: 13,
    specialties: ['Therapist', 'Physiotherapist'],
    description: 'Dr. Priyanka Mishra is a Physiotherapist in Belapur, Navi Mumbai and has an experience of 16 years in this field.',
    qualifications: ['BPTh/BPT'],
    clinicPhotos: [],
    reviews: [],
    fee: 400,
    isProfileClaimed: true,
    experience: 16,
    specialistExperience: 16,
    patientSatisfaction: 100,
    clinic: {
        name: 'Physio Plus Care & Cure',
        address: 'Shop Number 19, Saivihar Complex Sect 15 CBD Belapur, Navi Mumbai',
        rating: 5.0,
        timings: {
            days: 'Mon - Sat',
            hours: ['10:30 AM - 01:00 PM', '05:00 PM - 09:00 PM']
        },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 15,
        isVerified: true,
        phone: '09876543210'
    }
  },
  {
    id: 33,
    name: 'Dr. Nisha Lala',
    email: 'nisha.lala.physio@example.com',
    title: 'Physiotherapist',
    location: 'Belapur, Navi Mumbai',
    rating: 4.5,
    reviewCount: 0,
    specialties: ['Clinical Physiotherapist', 'Neurological Physiotherapist'],
    description: "A dedicated physiotherapist with a passion for helping individuals regain mobility, alleviate pain, and improve their overall quality of life. With 11 years of experience in the field, she specialize in musculoskeletal rehabilitation, sports injuries, post-operative recovery, etc. and she take a holistic approach to treatment, considering both the physical and emotional aspects of recovery. her goal is to empower you with the tools and strategies to not only recover from injury but to also maintain long-term health and strength. she believe in a personalized treatment plan that is tailored to each individual, incorporating the latest research, hands-on techniques, and patient education. Whether you're recovering from surgery, managing a chronic condition, or looking to prevent future injuries, she is here to support you every step of the way.",
    qualifications: ['BPTh/BPT', 'MPTh/MPT - Neurological Physiotherapist'],
    clinicPhotos: [],
    reviews: [],
    fee: 200,
    isProfileClaimed: false,
    experience: 11,
    specialistExperience: 11,
    patientSatisfaction: 90,
    clinic: {
        name: 'Physio Health Clinic',
        address: 'Number B 17, Indian Bank Officers Quarter, Sector 8b, Landmark: Bharatiya Vidhyapeeth College, Bharti Pharmacy Road, Navi Mumbai',
        rating: 4.5,
        timings: {
            days: 'Mon - Sun',
            hours: ['ON - CALL']
        },
        isOnlinePaymentAvailable: false,
        isPrime: false,
        maxWaitTime: 0,
        isVerified: true,
        phone: '09876543211'
    }
  }
];